# Тема 5. Векторные вычисления и массивы NumPy

**Дисциплина:** Основы программирования и анализа данных

**Цели занятия:**
- освоить создание и индексирование многомерных массивов NumPy;
- научиться применять векторизованные вычисления и механизм broadcasting;
- познакомиться с агрегирующими и статистическими функциями NumPy;
- научиться измерять выигрыш векторизованных операций по сравнению с циклами.

**Как работать с ноутбуком:**
1. Читайте теорию и запускайте примеры кода (`Shift + Enter`).
2. Экспериментируйте: меняйте данные в примерах и наблюдайте результат.
3. Задания выполняйте в ячейках под условием.
4. В конце — итоговая мини-задача, объединяющая все темы.

## 1. Создание и индексирование многомерных массивов

**NumPy** (Numerical Python) — базовая библиотека научных вычислений в Python. Её главный объект — **ndarray**: n-мерный массив элементов **одного типа**, хранящийся в непрерывном блоке памяти. Благодаря этому операции над массивами выполняются в десятки раз быстрее, чем над списками, а код получается компактнее.

Импортируют NumPy по стандартному соглашению:

```python
import numpy as np
```

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])            # одномерный массив из списка
m = np.array([[1, 2, 3],
              [4, 5, 6]])                # двумерный массив (матрица 2x3)

print(a)
print(m)
print('shape (форма):      ', m.shape)   # (2, 3): две строки, три столбца
print('ndim (размерность): ', m.ndim)    # 2
print('size (число элем.): ', m.size)    # 6
print('dtype (тип элем.):  ', m.dtype)   # int64

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
shape (форма):       (2, 3)
ndim (размерность):  2
size (число элем.):  6
dtype (тип элем.):   int64


In [2]:
# Типовые конструкторы массивов
print(np.arange(0, 10, 2))     # как range: от 0 до 10 с шагом 2
print(np.linspace(0, 1, 5))    # 5 равномерных точек на отрезке [0, 1]
print(np.zeros((2, 3)))        # матрица нулей 2x3
print(np.ones((3, 2)))         # матрица единиц 3x2
print(np.full((2, 2), 7.5))    # матрица, заполненная значением
print(np.eye(3))               # единичная матрица 3x3

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[7.5 7.5]
 [7.5 7.5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
m = np.arange(12)                # [0, 1, ..., 11]
print(m.reshape(3, 4))           # та же последовательность, форма 3x4
print(m.reshape(4, 3).T)         # транспонированная матрица

f = m.astype(np.float64)         # новый массив с другим типом данных
print(f.dtype, f[:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
float64 [0. 1. 2.]


### Индексирование и срезы

Синтаксис такой же, как у списков, но для многомерных массивов индексы перечисляются через запятую: `a[строка, столбец]`. Отрицательные индексы и срезы работают как обычно.

In [4]:
scores = np.array([[5, 4, 3, 5],
                   [4, 4, 4, 3],
                   [3, 5, 4, 5]])    # оценки 3 студентов по 4 предметам

print(scores[1, 2])       # 2-я строка, 3-й столбец
print(scores[0])          # вся 1-я строка
print(scores[:, 0])       # весь 1-й столбец
print(scores[0:2, 1:3])   # строки 0-1, столбцы 1-2
print(scores[-1])         # последняя строка
print(scores[::-1])       # строки в обратном порядке
print(scores[0, ::2])     # первая строка, каждый второй столбец

4
[5 4 3 5]
[5 4 3]
[[4 3]
 [4 4]]
[3 5 4 5]
[[3 5 4 5]
 [4 4 4 3]
 [5 4 3 5]]
[5 3]


**Важно: срез массива — это «представление» (view), а не копия.** Изменение среза меняет исходный массив (в отличие от срезов списков Python!). Если нужна независимая копия — используйте метод `.copy()`.

In [5]:
row = scores[0]
row[0] = 99                 # изменили срез...
print(scores)               # ...и исходная матрица изменилась тоже

scores[0, 0] = 5            # вернём значение обратно
row_copy = scores[0].copy() # независимая копия
row_copy[0] = -1
print(scores[0], '| копия:', row_copy)

[[99  4  3  5]
 [ 4  4  4  3]
 [ 3  5  4  5]]
[5 4 3 5] | копия: [-1  4  3  5]


### Булевы маски и выбор по условию

Условие над массивом возвращает **булеву маску** — массив из `True` и `False`. Маской можно отфильтровать элементы или использовать её в агрегатах. Условия комбинируют операторами `&` (И), `|` (ИЛИ), `~` (НЕ) — каждое отдельное условие обязательно берут в скобки.

In [6]:
data = np.array([15, 22, 8, 41, 6, 33, 27])

mask = data > 20
print(mask)                             # [False  True False  True False  True  True]
print(data[mask])                       # только элементы больше 20
print(data[data % 2 == 0])              # фильтрация в одну строку
print(data[(data > 10) & (data < 35)])  # И: скобки обязательны!
print(data[(data < 10) | (data > 40)])  # ИЛИ
print(data[~(data > 20)])               # НЕ

print(np.where(data > 20, 1, 0))        # замена по условию: маска -> числа
print(data[np.array([0, 3, 6])])        # fancy indexing: выбор по набору индексов

[False  True False  True False  True  True]
[22 41 33 27]
[22  8  6]
[15 22 33 27]
[ 8 41  6]
[15  8  6]
[0 1 0 1 0 1 1]
[15 41 27]


### Задание 1. Создание массивов

1. Создайте массив `numbers` из целых чисел от 1 до 12 с помощью `np.arange` и измените его форму на 3x4 (`reshape`).
2. Выведите `shape`, `ndim`, `size` и `dtype` полученной матрицы.
3. Создайте матрицу `grid` 4x4 из нулей и замените её главную диагональ единицами (подсказка: `np.eye` или цикл по `grid[i, i]`).
4. Создайте массив из 8 равномерных точек на отрезке `[0, 2]` с помощью `np.linspace`.
5. Приведите `numbers` к типу `float64`, не изменяя исходный массив.

In [7]:
# Решение задания 1

numbers=np.arange(1, 13).reshape(3, 4)
print('1:', '\n', numbers, '\n')
print('2:', 'shape:', numbers.shape, 'ndim:', numbers.ndim, 'size:', numbers.size, 'dtype:', numbers.dtype, '\n')
grid=np.zeros((4, 4))
for i in range(4):
    grid[i, i]=1
print('3:', '\n', grid, '\n')
a=np.linspace(0, 2, 8)
print('4:', a, '\n')
new=numbers.copy()
new = new.astype(np.float64)
print('5:', '\n', new, '\n')




1: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

2: shape: (3, 4) ndim: 2 size: 12 dtype: int64 

3: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

4: [0.         0.28571429 0.57142857 0.85714286 1.14285714 1.42857143
 1.71428571 2.        ] 

5: 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] 



### Задание 2. Индексирование и маски

Дана матрица наблюдений (данные в ячейке ниже).

1. Выведите значение в 3-й строке и 2-м столбце.
2. Выведите последний столбец матрицы.
3. Выведите подматрицу из первых двух строк и последних двух столбцов.
4. Выведите только те значения, которые превышают среднее по всей матрице.
5. С помощью `np.where` получите массив, где отрицательные значения заменены нулями (исходный не менять).
6. Посчитайте число отрицательных значений (подсказка: `sum` от маски).

In [8]:
# Решение задания 2
observations = np.array([
    [ 12,  -5,   3,  20],
    [ -8,   7,  15,   4],
    [  9,  -2,  11,  -6],
    [ 14,   0,  -9,   8],
])

print('1:', observations[2, 1], '\n')
print('2:', observations[:, -1], '\n')
print('3:', '\n', observations[:2, -2:], '\n')
print('4:', observations[np.mean(observations)<observations], '\n')
print('5:', '\n', np.where(observations<0, 0, observations), '\n')
print('6:', np.sum(observations<0))

1: -2 

2: [20  4 -6  8] 

3: 
 [[ 3 20]
 [15  4]] 

4: [12 20  7 15  9 11 14  8] 

5: 
 [[12  0  3 20]
 [ 0  7 15  4]
 [ 9  0 11  0]
 [14  0  0  8]] 

6: 5


## 2. Векторизация вычислений и broadcasting

**Векторизация** — применение операции ко всему массиву сразу, без явного цикла. Операторы `+`, `-`, `*`, `/`, `**` работают **поэлементно**, а математические функции NumPy (`np.sqrt`, `np.exp`, `np.sin` и др.) обрабатывают массив целиком. Такие операции реализованы на языке C и выполняются на порядки быстрее циклов Python.

In [9]:
prices = np.array([100.0, 250.0, 80.0, 320.0])
print(prices * 0.85)              # скидка 15% сразу всем товарам

q = np.array([1.0, 2.0, 3.0, 4.0])
print(q ** 2 + 2 * q + 1)         # выражение над всем массивом разом
print(np.sqrt(q))                 # универсальные функции (ufunc)
print(np.round(np.exp(q), 2))

# Для сравнения: список так не умеет
print([1, 2, 3] * 2)              # список повторится, а не умножится

[ 85.  212.5  68.  272. ]
[ 4.  9. 16. 25.]
[1.         1.41421356 1.73205081 2.        ]
[ 2.72  7.39 20.09 54.6 ]
[1, 2, 3, 1, 2, 3]


### Broadcasting

**Broadcasting** — механизм, который позволяет NumPy выполнять операции над массивами **разных форм** без копирования данных. Правила:

1. Формы массивов сравниваются **с конца**.
2. Размерности совместимы, если они **равны** или одна из них равна **1**.
3. Массив с меньшим числом размерностей дополняется ведущими единицами.
4. Размерность, равная 1, «растягивается» до размера соответствующей размерности второго массива.

Пример: матрица `(3, 4)` плюс массив `(4,)` — массив дополняется до `(1, 4)` и складывается с каждой строкой матрицы.

In [10]:
m = np.arange(1, 13).reshape(3, 4)
print('Матрица 3x4:')
print(m)

row = np.array([10, 20, 30, 40])        # форма (4,)
print('Матрица + строка (4,):')
print(m + row)                           # строка прибавилась к каждой строке

col = np.array([[1], [10], [100]])       # форма (3, 1)
print('Матрица + столбец (3,1):')
print(m + col)                           # столбец прибавился к каждому столбцу

Матрица 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Матрица + строка (4,):
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]
Матрица + столбец (3,1):
[[  2   3   4   5]
 [ 15  16  17  18]
 [109 110 111 112]]


In [11]:
temps_c = np.array([15.0, 18.0, 21.0, 24.0])
temps_f = temps_c * 9 / 5 + 32           # перевод в Фаренгейты одной строкой
print(temps_f)

# Центрирование данных: вычитаем из каждого столбца его среднее
measurements = np.array([[10.0, 20.0, 30.0],
                         [12.0, 18.0, 34.0],
                         [11.0, 22.0, 29.0],
                         [ 9.0, 24.0, 27.0]])
col_means = measurements.mean(axis=0, keepdims=True)   # форма (1, 3)
print('Средние по столбцам:', col_means)
centered = measurements - col_means                    # broadcasting
print('Средние центрированных данных:', centered.mean(axis=0))   # почти нули

[59.  64.4 69.8 75.2]
Средние по столбцам: [[10.5 21.  30. ]]
Средние центрированных данных: [0. 0. 0.]


### Задание 3. Broadcasting

Три магазина продают одни и те же 4 товара. В ячейке ниже: `prices` — цены товаров, `sales` — проданное количество (строка — магазин, столбец — товар).

1. Одной операцией рассчитайте матрицу выручки: количество умножить на цену (broadcasting).
2. Найдите суммарную выручку каждого магазина (`sum` с `axis=1`).
3. Цены выросли на 7%: получите новый массив цен, не изменяя исходный.
4. Из каждого значения `sales` вычтите среднее по соответствующему столбцу (`mean` с `axis=0` и `keepdims=True`).
5. Проверьте: средние по столбцам результата п. 4 должны быть (почти) нулями.

In [12]:
# Решение задания 3
prices = np.array([120.0, 350.0, 90.0, 560.0])
sales = np.array([
    [10, 2, 25, 1],
    [ 4, 5, 30, 2],
    [ 7, 0, 22, 3],
])
print('1:', '\n', sales*prices)
print('2:', '\n', (sales*prices).sum(axis=1, keepdims=True), '\n')
new=prices.copy()
new=new*1.07
print('3:', '\n', new)
print('4:', '\n', sales-sales.mean(axis=0, keepdims=True), '\n')
print('5:', (sales-sales.mean(axis=0, keepdims=True)).mean(axis=0))


1: 
 [[1200.  700. 2250.  560.]
 [ 480. 1750. 2700. 1120.]
 [ 840.    0. 1980. 1680.]]
2: 
 [[4710.]
 [6050.]
 [4500.]] 

3: 
 [128.4 374.5  96.3 599.2]
4: 
 [[ 3.         -0.33333333 -0.66666667 -1.        ]
 [-3.          2.66666667  4.33333333  0.        ]
 [ 0.         -2.33333333 -3.66666667  1.        ]] 

5: [ 0.00000000e+00 -1.48029737e-16 -1.18423789e-15  0.00000000e+00]


## 3. Агрегирующие и статистические функции NumPy

NumPy содержит готовый набор статистических функций. Большинство работает и как функция (`np.mean(a)`), и как метод массива (`a.mean()`).

In [13]:
data = np.array([4, 8, 15, 16, 23, 42])

print('sum    ', data.sum())                             # сумма
print('mean   ', data.mean())                            # среднее
print('std    ', round(data.std(), 2))                   # стандартное отклонение
print('var    ', round(data.var(), 2))                   # дисперсия
print('min/max', data.min(), data.max())
print('argmax/argmin:', data.argmax(), data.argmin())    # ИНДЕКСЫ экстремумов
print('median ', np.median(data))                        # медиана (только функция)
print('p75    ', np.percentile(data, 75))                # 75-й перцентиль
print('cumsum ', data.cumsum())                          # накопленная сумма

sum     108
mean    18.0
std     12.32
var     151.67
min/max 4 42
argmax/argmin: 5 0
median  15.5
p75     21.25
cumsum  [  4  12  27  43  66 108]


### Агрегация по осям: параметр axis

Для многомерных массивов агрегаты считают вдоль **осей**. Правило запоминания: `axis=0` — «вдоль строк», в результате по одному значению на каждый столбец; `axis=1` — «вдоль столбцов», по одному значению на каждую строку.

In [14]:
m = np.arange(1, 13).reshape(3, 4)
print('Матрица:')
print(m)
print('Сумма всех элементов:   ', m.sum())
print('Суммы по столбцам (0): ', m.sum(axis=0))    # 4 значения - по числу столбцов
print('Суммы по строкам (1):  ', m.sum(axis=1))    # 3 значения - по числу строк
print('Средние по строкам:    ', m.mean(axis=1))
print('Максимумы по столбцам: ', m.max(axis=0))

Матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Сумма всех элементов:    78
Суммы по столбцам (0):  [15 18 21 24]
Суммы по строкам (1):   [10 26 42]
Средние по строкам:     [ 2.5  6.5 10.5]
Максимумы по столбцам:  [ 9 10 11 12]


### Пропуски: nan-функции

`np.nan` (not a number) — стандартное обозначение пропущенного значения в аналитических данных. Обычные функции возвращают nan, если в данных есть хотя бы один пропуск, поэтому существуют варианты с префиксом `nan`, игнорирующие пропуски.

In [50]:
readings = np.array([1.0, 2.5, np.nan, 4.0, 3.5])

print(readings.mean())           # nan: один пропуск испортил весь результат
print(np.nanmean(readings))      # среднее без учёта пропусков
print(np.nanmax(readings))
print(np.isnan(readings))        # маска пропусков
print('Пропусков:', np.isnan(readings).sum())

nan
2.75
4.0
[False False  True False False]
Пропусков: 1


### Задание 4. Агрегации и статистики

Дана матрица оценок: 5 студентов (строки) по 4 предметам (столбцы).

1. Посчитайте средний балл каждого студента (`axis=1`) и округлите до сотых.
2. Посчитайте средний балл по каждому предмету (`axis=0`).
3. Найдите индекс студента с максимальным средним баллом (`argmax`) и его средний балл.
4. Посчитайте количество пятёрок и количество двоек во всей матрице (через маски).
5. Найдите медиану и стандартное отклонение всех оценок.
6. Студент с индексом 2 пересдал последний предмет (столбец 3) на 5: обновите значение в матрице и заново посчитайте его средний балл.

In [16]:
# Решение задания 4
grades = np.array([
    [5, 4, 3, 4],
    [4, 4, 4, 3],
    [3, 5, 4, 2],
    [5, 5, 5, 4],
    [3, 2, 3, 4],
])
print('1:', '\n', (grades.mean(axis=1, keepdims=True).round(2)), '\n')
print('2:', grades.mean(axis=0), '\n')
print('3:', 'индекс:', (grades.mean(axis=1)).argmax(), 'средний балл:', (grades.mean(axis=1)).max(), '\n')
print('4:', 'пятерки:', (grades==5).sum(), 'двойки:', (grades==2).sum(), '\n')
print('5:', 'медиана:', np.median(grades), 'стандартное отклонение:', grades.std(), '\n')
grades[2, 3]=5
print('6:', grades[2].mean())

1: 
 [[4.  ]
 [3.75]
 [3.5 ]
 [4.75]
 [3.  ]] 

2: [4.  4.  3.8 3.4] 

3: индекс: 3 средний балл: 4.75 

4: пятерки: 5 двойки: 2 

5: медиана: 4.0 стандартное отклонение: 0.9273618495495703 

6: 4.25


## 4. Сравнение циклических и векторизованных операций

Проверим на практике, насколько векторизация быстрее цикла. Для замеров в Jupyter есть магия `%timeit` (многократно повторяет код и усредняет время), а для самостоятельных замеров — модуль `time` и функция `perf_counter`.

In [17]:
import numpy as np
from time import perf_counter

rng = np.random.default_rng(42)          # генератор случайных чисел с «семенем»
n = 1_000_000
x = rng.random(n)                        # массив из n случайных чисел на [0, 1)
x_list = x.tolist()                      # те же числа в виде списка Python

# Вариант 1: классический цикл по списку
start = perf_counter()
total = 0.0
for v in x_list:
    total += v * v
loop_time = perf_counter() - start

# Вариант 2: векторизованная операция NumPy
start = perf_counter()
result = np.sum(x * x)
vector_time = perf_counter() - start

print(f'Цикл по списку:     {loop_time * 1000:8.1f} мс')
print(f'Векторизация NumPy: {vector_time * 1000:8.2f} мс')
print(f'Ускорение: примерно в {loop_time / vector_time:.0f} раз')
print('Результаты совпадают:', np.isclose(total, result))

Цикл по списку:        191.2 мс
Векторизация NumPy:     3.69 мс
Ускорение: примерно в 52 раз
Результаты совпадают: True


In [18]:
# Магия %timeit: повторяет замер много раз и даёт устойчивую оценку
%timeit sum(v * v for v in x_list)   # сумма квадратов по списку (генератор)
%timeit np.sum(x * x)                # векторизованный вариант

51.7 ms ± 2.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.62 ms ± 29.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Почему векторизация быстрее:**

- на каждой итерации цикла Python интерпретатор проверяет типы и создаёт объекты — это дорого;
- NumPy выполняет операцию один раз над всем массивом скомпилированным кодом на C;
- элементы массива лежат в непрерывной памяти и имеют один тип — нет накладных расходов на отдельные объекты.

**Когда цикл всё же уместен:** небольшие данные; логика, которую нельзя выразить поэлементными операциями (например, значение зависит от предыдущего шага); шаги с побочными эффектами (печать, запись в файл).

**Правило:** если операцию можно записать формулой над массивом — записывайте её векторно.

### Задание 5. Измеряем скорость

1. Создайте массив `x` из `1_000_000` случайных чисел (`default_rng`, метод `random`) и его списочную копию (`tolist`).
2. Напишите функцию `normalize_loop(values)`: циклом строит и возвращает список, где каждое значение поделено на максимум.
3. Векторный вариант — одна строка: `x / x.max()` (для массива).
4. Измерьте время обоих вариантов (`perf_counter` или `%timeit`).
5. Выведите, во сколько раз векторизация быстрее.
6. Убедитесь, что результаты совпадают: `np.allclose`.

In [19]:
# Решение задания 5
rng=np.random.default_rng()
x = rng.random(1_000_000) 
tolist=x.tolist()

def normalize_loop(values):
    maxx=max(values)
    new=[]
    for x in values:
        new.append(x/maxx)
    return new

start=perf_counter()
loop_r=normalize_loop(tolist)
loop_time = perf_counter() - start

start=perf_counter()
vector_r=x / x.max()
vector_time = perf_counter() - start

print("Время цикла:", loop_time)
print("Время векторизации:", vector_time)
print("Векторизация быстрее в",loop_time / vector_time,"раз")
print('Результаты совпадают:', np.allclose(vector_r, loop_r))

Время цикла: 0.14645310000196332
Время векторизации: 0.013595999997050967
Векторизация быстрее в 10.771778466735043 раз
Результаты совпадают: True


## Итоговая мини-задача

Метеостанция вела наблюдения в течение года: 12 месяцев по 30 дней. Данные создаются в ячейке ниже с фиксированным «семенем», поэтому у всех получатся одинаковые значения. Индекс месяца 0 — январь.

Реализуйте конвейер из функций:

1. `generate_temperatures(seed=2024)` — возвращает массив 12x30 по модели: `10 + 15 * sin((месяц - 3) / 12 * 2 * pi) + шум N(0, 3)` (шум — `rng.normal(0, 3, size=(12, 30))`);
2. `monthly_mean(temps)` — массив средних температур по месяцам, округлённых до одного знака;
3. `warmest_month(temps)` — возвращает номер самого тёплого месяца (от 1 до 12) и его среднюю температуру;
4. `hot_days(temps, threshold=25)` — число дней в году с температурой выше `threshold` (значение по умолчанию обязательно);
5. `anomaly(temps)` — отклонение каждой дневной температуры от среднего по её месяцу (broadcasting с `keepdims=True`);
6. `climate_report(temps)` — возвращает словарь: средняя температура за год, самый тёплый и самый холодный месяцы, число дней с температурой ниже 0.

**Требования:** у каждой функции — докстринг; весь числовой код — без циклов, только векторные операции; печать результатов — только в конце конвейера.

In [49]:
import numpy as np

# Данные для итоговой задачи
rng = np.random.default_rng(2024)
month_index = np.arange(12).reshape(12, 1)
seasonal = 10 + 15 * np.sin((month_index - 3) / 12 * 2 * np.pi)
TEMPS = seasonal + rng.normal(0, 3, size=(12, 30))

# Решение итоговой задачи
def generate_temperatures(seed=2024):
    """Создаёт массив температур размером 12x30 по заданной модели."""
    rng = np.random.default_rng(2024)
    month_index = np.arange(12).reshape(12, 1)
    seasonal = 10 + 15 * np.sin((month_index - 3) / 12 * 2 * np.pi)
    TEMPS = seasonal + rng.normal(0, 3, size=(12, 30))
    return TEMPS

def monthly_mean(temps):
    """массив средних температур по месяцам, округлённых до одного знака"""
    return np.round(temps.mean(axis=1), 1)

def warmest_month(temps):
    """возвращает номер самого тёплого месяца (от 1 до 12) и его среднюю температуру"""
    return np.argmax(temps.mean(axis=1))+1, round(max(temps.mean(axis=1)), 1)


def hot_days(temps, threshold=25):
    """число дней в году с температурой выше `threshold`"""
    return (temps>threshold).sum()

def anomaly(temps):
    """отклонение каждой дневной температуры от среднего по её месяцу"""
    return temps-temps.mean(axis=1, keepdims=True)

def climate_report(temps):
    """возвращает словарь: средняя температура за год, самый тёплый и самый холодный месяцы, число дней с температурой ниже 0."""
    a=temps.mean(axis=1)
    b=np.argmax(a)
    c=np.argmin(a)
    return {
        "Средняя температура за год:": round(temps.mean(), 1),
        "Самый тёплый месяц:": b+1,
        "Средняя температура тёплого месяца:": round(a[b], 1),
        "Самый холодный месяц:": c+1,
        "Средняя температура холодного месяца:": round(a[c], 1),
        "Число дней с температоруй ниже 0:": (temps<0).sum()
    }
    
temps = generate_temperatures()
print("Средние температуры по месяцам:", monthly_mean(temps), '\n')
print("Номер самого тёплого месяца и его средняя температура:", warmest_month(temps)[0], 'Месяц', '  ', warmest_month(temps)[1], 'Средняя температура', '\n')
print("Число дней в году с температурой выше 25:", hot_days(temps), 'дней', '\n')
print("Отчет:")
for key, value in  climate_report(temps).items():
    print(key, value)
print("")
print("Отклонение каждой дневной температуры от среднего по её месяцу:", '\n', anomaly(temps))

Средние температуры по месяцам: [-4.9 -2.7  2.8  9.4 17.  23.3 24.  23.6 18.1 10.2  2.5 -4.5] 

Номер самого тёплого месяца и его средняя температура: 7 Месяц    24.0 Средняя температура 

Число дней в году с температурой выше 25: 30 дней 

Отчет:
Средняя температура за год: 9.9
Самый тёплый месяц: 7
Средняя температура тёплого месяца: 24.0
Самый холодный месяц: 1
Средняя температура холодного месяца: -4.9
Число дней с температоруй ниже 0: 83

Отклонение каждой дневной температуры от среднего по её месяцу: 
 [[ 2.99806315e+00  4.83725265e+00  3.35165111e+00 -3.00804602e+00
  -4.26690776e+00  1.13081590e-01  2.49554528e+00  1.43905292e+00
   5.34234925e+00  2.16402294e+00  1.83077119e+00 -2.28247504e+00
  -3.41165858e+00  4.36470928e+00  5.82297339e-02  2.34605288e+00
  -4.21777600e+00 -1.39761968e+00 -3.96178238e+00 -2.41554353e+00
   2.62068176e+00 -4.53025145e+00 -1.69078596e+00  4.02858241e-01
  -2.09391839e+00 -8.45376754e-01 -7.54092098e-01  1.16590823e+00
  -1.38227112e+00  7.282

## Контрольные вопросы

1. Чем массив NumPy принципиально отличается от списка Python? Назовите минимум три отличия.

Ответ: 1)NumPy содержит элементы одного типа, а список может содержать разные типы.
       2)NumPy быстрее обрабатывает большие объёмы числовых данных.
       3)NumPy намного удобнее для работы с многомерными данными и матрицами.

2. Что означают записи `a[1]`, `a[1, 2]` и `a[1][2]` для двумерного массива? Какой из вариантов предпочтительнее и почему?

Ответ:a[1] — берём вторую строку; a[1, 2] — берём элемент второй строки и третьего столбца; a[1][2] — сначала берём вторую строку, а потом из неё третий элемент(два этапа вместо одного). Вариант a[1, 2] лучше т.к. он быстрее.

3. Почему срез массива — это представление (view)? Как получить независимую копию?

Ответ: Срез NumPy по умолчанию создаёт представление исходного массива, а не новый массив.Изменение среза меняет исходный массив (в отличие от срезов списков Python). Если нужна независимая копия — используется метод `.copy()`.

4. Сформулируйте правила broadcasting. Совместимы ли формы `(4, 1)` и `(1, 3)`? Какая форма получится у результата?

Ответ:1) Формы массивов сравниваются **с конца**.
      2) Размерности совместимы, если они **равны** или одна из них равна **1**.
      3) Массив с меньшим числом размерностей дополняется ведущими единицами.
      4) Размерность, равная 1, «растягивается» до размера соответствующей размерности второго массива.
    Совместимы, результат:(4, 3)

5. Что вернёт `m.sum(axis=0)` для матрицы `m` формы `(3, 4)`? А `m.mean(axis=1)`?

Ответ: 1)Вернет 1 строку с 4 столбцами с суммой по столбцам (1, 4). 
       2)Вернет 1 столбец с 3 строками с средним значением по строкам (3, 1)

6. Зачем скобки в выражении `(data > 0) & (data < 10)`? Что произойдёт без них?

Ответ: Скобки нужны, чтобы сначала отдельно получить две логические маски, а потом объединить их через &. Без скобок Python неправильно обработает приоритет операторов и можно получить ошибку или неправильное выражение.

7. Чем `argmax` отличается от `max`? В каких задачах нужен именно `argmax`?

Ответ: 'argmax' возвращает индекс максимального значения, 'max' возвращает максимальное значение. Argmax используется при поиске, например, самой дорогой вещи в магазине(с max мы будем знать только её стоимость).

8. Почему векторизованные операции NumPy быстрее циклов Python?

Ответ:Математические функции NumPy обрабатывают массив целиком. Такие операции реализованы на языке C и выполняются на порядки быстрее циклов Python, потому что циклы выполняются поэлементно.

9. Когда цикл всё же предпочтительнее векторизации?

Ответ: Когда цикл всё же уместен: небольшие данные; логика, которую нельзя выразить поэлементными операциями (например, значение зависит от предыдущего шага); шаги с побочными эффектами (печать, запись в файл).

10. Чем `np.nanmean` отличается от `mean`? Когда это критично?

Ответ:`np.nan` (not a number) — стандартное обозначение пропущенного значения в аналитических данных. Обычные функции возвращают nan, если в данных есть хотя бы один пропуск, поэтому существуют варианты с префиксом `nan`, игнорирующие пропуски. Это критично при работе с реальными данными, где могут быть пропуски. Если использовать обычный mean, пропущенное значение может сделать весь результат NaN.

## Что посмотреть дополнительно

- Официальная документация NumPy (numpy.org): разделы *The absolute basics for beginners* и *Broadcasting*.
- Сборник *100 NumPy exercises* (репозиторий rougier/numpy-100 на GitHub) — задачи от простых к сложным.
- Генерация случайных чисел: документация модуля `numpy.random` (класс `Generator`, функция `default_rng`).
- NumPy — фундамент библиотеки `pandas`, которая будет изучаться в следующей теме.